"""rename address

Revision ID: 636de4a04554
Revises: b5dc093ad8f2
Create Date: 2025-06-10 23:16:40.872035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '636de4a04554'
down_revision = 'b5dc093ad8f2'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
